# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, overload

import shape_extensions
from numpy._shapes import binary_ufunc_ir, matmul_2d_ir, reduce_ir
from shape_extensions import Dim, uses_shape_dsl

from . import random as random

type _Shape = tuple[int, ...]
type _AnyShape = tuple[Any, ...]
type _Axis = int | tuple[int, ...] | None

class generic: ...
class bool_(generic): ...
class float32(generic): ...
class float64(generic): ...
class int32(generic): ...
class int64(generic): ...

class dtype[Scalar = Any]:
    @overload
    def __new__[ScalarT: generic](cls, dtype: type[ScalarT]) -> dtype[ScalarT]: ...
    @overload
    def __new__(cls, dtype: Any = ...) -> dtype: ...
    def __init__(self, dtype: Any = ...) -> None: ...

@shape_extensions.shaped_array(shape="Shape")
class ndarray[Shape: _Shape = _AnyShape, DType = Any]:
    shape: Shape
    dtype: DType
    def __add__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __radd__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __truediv__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __rtruediv__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __mul__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __rmul__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __neg__(self) -> ndarray[Shape, DType]: ...
    def __pos__(self) -> ndarray[Shape, DType]: ...
    def __pow__(self, other: int | float) -> ndarray[Shape, DType]: ...
    # TODO: Bridge until operator dunders/bound methods can share the DSL-backed
    # `np.matmul` rule and diagnostics.
    def __matmul__[N, M, P](
        self: ndarray[tuple[Dim[N], Dim[M]], DType],
        other: ndarray[tuple[Dim[M], Dim[P]]],
    ) -> ndarray[tuple[Dim[N], Dim[P]], DType]: ...

def abs[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def exp[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log2[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def log10[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def sqrt[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def power[Shape: _Shape](x1: ndarray[Shape], x2: int | float, /) -> ndarray[Shape]: ...
@uses_shape_dsl(binary_ufunc_ir)
def minimum(x1: ndarray, x2: ndarray, /) -> ndarray: ...
@uses_shape_dsl(binary_ufunc_ir)
def maximum(x1: ndarray, x2: ndarray, /) -> ndarray: ...
@uses_shape_dsl(binary_ufunc_ir)
def arctan2(x1: ndarray, x2: ndarray, /) -> ndarray: ...
def sin[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def cos[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def tan[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def arcsin[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def floor[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def ceil[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def round[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def trunc[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def clip[Shape: _Shape](
    a: ndarray[Shape], a_min: int | float, a_max: int | float
) -> ndarray[Shape]: ...
def negative[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
@uses_shape_dsl(reduce_ir)
def sum(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def mean(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def min(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(reduce_ir)
def max(a: ndarray, axis: _Axis = None, *, keepdims: bool = False) -> ndarray: ...
@uses_shape_dsl(matmul_2d_ir)
def matmul(a: ndarray, b: ndarray, /) -> ndarray: ...

# TODO(stroxler): Replace these finite tuple-shape constructor overloads with a
# generic `Shape: tuple[int, ...]` overload once carrier shapes flow through
# downstream shaped-array operations without degrading to unknown.
@overload
def zeros[N, ScalarT: generic](
    shape: Dim[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def zeros[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def zeros[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def zeros[N, ScalarT: generic](
    shape: Dim[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def zeros[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def zeros[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def zeros[N](
    shape: Dim[N], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def zeros[N](
    shape: tuple[Dim[N]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def zeros[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[float64]]: ...
@overload
def zeros[N](shape: Dim[N], dtype: Any, order: str = ...) -> ndarray[tuple[Dim[N]]]: ...
@overload
def zeros[N](
    shape: tuple[Dim[N]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def zeros[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def ones[N, ScalarT: generic](
    shape: Dim[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def ones[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def ones[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def ones[N, ScalarT: generic](
    shape: Dim[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def ones[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def ones[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def ones[N](
    shape: Dim[N], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def ones[N](
    shape: tuple[Dim[N]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def ones[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[float64]]: ...
@overload
def ones[N](shape: Dim[N], dtype: Any, order: str = ...) -> ndarray[tuple[Dim[N]]]: ...
@overload
def ones[N](
    shape: tuple[Dim[N]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def ones[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def full[N, ScalarT: generic](
    shape: Dim[N],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def full[N, ScalarT: generic](
    shape: tuple[Dim[N]],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def full[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]],
    fill_value: Any,
    dtype: type[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def full[N, ScalarT: generic](
    shape: Dim[N],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def full[N, ScalarT: generic](
    shape: tuple[Dim[N]],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def full[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]],
    fill_value: Any,
    dtype: dtype[ScalarT],
    order: str = ...,
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def full[N](
    shape: Dim[N], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def full[N](
    shape: tuple[Dim[N]], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def full[N, M](
    shape: tuple[Dim[N], Dim[M]], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def empty[N, ScalarT: generic](
    shape: Dim[N], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def empty[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def empty[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def empty[N, ScalarT: generic](
    shape: Dim[N], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def empty[N, ScalarT: generic](
    shape: tuple[Dim[N]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[ScalarT]]: ...
@overload
def empty[N, M, ScalarT: generic](
    shape: tuple[Dim[N], Dim[M]], dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[ScalarT]]: ...
@overload
def empty[N](
    shape: Dim[N], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def empty[N](
    shape: tuple[Dim[N]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N]], dtype[float64]]: ...
@overload
def empty[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]], dtype[float64]]: ...
@overload
def empty[N](shape: Dim[N], dtype: Any, order: str = ...) -> ndarray[tuple[Dim[N]]]: ...
@overload
def empty[N](
    shape: tuple[Dim[N]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def empty[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any, order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def eye[N, ScalarT: generic](
    N: Dim[N], M: None = ..., k: int = ..., *, dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def eye[N, ScalarT: generic](
    N: Dim[N], M: None, k: int, dtype: type[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def eye[N, ScalarT: generic](
    N: Dim[N], M: None = ..., k: int = ..., *, dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def eye[N, ScalarT: generic](
    N: Dim[N], M: None, k: int, dtype: dtype[ScalarT], order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def eye[N](
    N: Dim[N], M: None = ..., k: int = ..., dtype: None = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[float64]]: ...
@overload
def eye[N](
    N: Dim[N], M: None = ..., k: int = ..., dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]]]: ...
@overload
def identity[N, ScalarT: generic](
    n: Dim[N], dtype: type[ScalarT], *, like: Any = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def identity[N, ScalarT: generic](
    n: Dim[N], dtype: dtype[ScalarT], *, like: Any = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[ScalarT]]: ...
@overload
def identity[N](
    n: Dim[N], dtype: None = ..., *, like: Any = ...
) -> ndarray[tuple[Dim[N], Dim[N]], dtype[float64]]: ...
@overload
def identity[N](
    n: Dim[N], dtype: Any, *, like: Any = ...
) -> ndarray[tuple[Dim[N], Dim[N]]]: ...
