# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, overload

import shape_extensions
from shape_extensions import Dim

type _Shape = tuple[int, ...]
type _AnyShape = tuple[Any, ...]

@shape_extensions.shaped_array(shape="Shape")
class ndarray[Shape: _Shape = _AnyShape, DType = Any]:
    shape: Shape
    def __add__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __mul__(self, other: int | float) -> ndarray[Shape, DType]: ...
    def __neg__(self) -> ndarray[Shape, DType]: ...
    def __pos__(self) -> ndarray[Shape, DType]: ...
    def __pow__(self, other: int | float) -> ndarray[Shape, DType]: ...

def abs[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...
def negative[Shape: _Shape](x: ndarray[Shape]) -> ndarray[Shape]: ...

# TODO(stroxler): Replace these finite tuple-shape constructor overloads with a
# generic `Shape: tuple[int, ...]` overload once carrier shapes flow through
# downstream shaped-array operations without degrading to unknown.
@overload
def zeros[N](
    shape: Dim[N], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def zeros[N](
    shape: tuple[Dim[N]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def zeros[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def ones[N](
    shape: Dim[N], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def ones[N](
    shape: tuple[Dim[N]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def ones[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def full[N](
    shape: Dim[N], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def full[N](
    shape: tuple[Dim[N]], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def full[N, M](
    shape: tuple[Dim[N], Dim[M]], fill_value: Any, dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
@overload
def empty[N](
    shape: Dim[N], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def empty[N](
    shape: tuple[Dim[N]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N]]]: ...
@overload
def empty[N, M](
    shape: tuple[Dim[N], Dim[M]], dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[M]]]: ...
def eye[N](
    N: Dim[N], M: None = ..., k: int = ..., dtype: Any = ..., order: str = ...
) -> ndarray[tuple[Dim[N], Dim[N]]]: ...
def identity[N](
    n: Dim[N], dtype: Any = ..., *, like: Any = ...
) -> ndarray[tuple[Dim[N], Dim[N]]]: ...
