# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import Any, overload, Self

from shape_extensions import shaped_array

class device:
    def __init__(self, type: str, index: int = 0) -> None: ...

@shaped_array(shape="Shape")
class Tensor[*Shape]:
    shape: tuple[int, ...]
    requires_grad: bool
    dtype: Any
    def __getitem__(
        self,
        index: int
        | slice
        | tuple[int | slice | Tensor | list[int] | None, ...]
        | Tensor
        | list[int],
    ) -> Tensor: ...
    def __matmul__(self: Tensor, other: Tensor) -> Tensor: ...
    def __add__(self, other: Tensor | float | int) -> Self: ...
    def __sub__(self, other: Tensor | float | int) -> Self: ...
    def __mul__(self, other: Tensor | float | int) -> Self: ...
    def __truediv__(self, other: Tensor | float | int) -> Self: ...
    def __radd__(self, other: float | int) -> Self: ...
    def __rsub__(self, other: float | int) -> Self: ...
    def __rmul__(self, other: float | int) -> Self: ...
    def __neg__(self) -> Self: ...
    def __eq__(self, other: Tensor | float | int) -> Self: ...  # type: ignore[override]
    def __lt__(self, other: Tensor | float | int) -> Self: ...
    def __gt__(self, other: Tensor | float | int) -> Self: ...
    @overload
    def reshape(self: Tensor, *shape: int) -> Tensor: ...
    @overload
    def reshape(self: Tensor, shape: tuple[int, ...]) -> Tensor: ...
    @overload
    def view(self: Tensor, *shape: int) -> Tensor: ...
    @overload
    def view(self: Tensor, shape: tuple[int, ...]) -> Tensor: ...
    def flatten(self: Tensor, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
    def transpose(self: Tensor, dim0: int, dim1: int) -> Tensor: ...
    def unsqueeze(self: Tensor, dim: int) -> Tensor: ...
    def squeeze(self: Tensor, dim: int = ...) -> Tensor: ...
    @overload
    def tile(self: Tensor, *reps: int) -> Tensor: ...
    @overload
    def tile(self: Tensor, reps: tuple[int, ...]) -> Tensor: ...
    @overload
    def permute(self: Tensor, *dims: int) -> Tensor: ...
    @overload
    def permute(self: Tensor, dims: tuple[int, ...]) -> Tensor: ...
    def t(self: Tensor) -> Tensor: ...
    def contiguous(self) -> Self: ...
    def detach(self) -> Self: ...
    def clone(self) -> Self: ...
    def dim(self) -> int: ...
    def size(self, dim: int = ...) -> int: ...
    def item(self) -> float: ...
    def tolist(self) -> list[Any]: ...
    def to(self, device: Any = ..., dtype: Any = ...) -> Self: ...

def randn(*size: int, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def rand(*size: int, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def zeros(*size: int, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def ones(*size: int, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def empty(*size: int, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def full(
    size: tuple[int, ...], fill_value: float, dtype: Any = ..., device: Any = ...
) -> Tensor: ...
def eye(n: int, m: int = ..., dtype: Any = ..., device: Any = ...) -> Tensor: ...
def arange(
    start: float = ...,
    end: float = ...,
    step: float = ...,
    dtype: Any = ...,
    device: Any = ...,
) -> Tensor: ...
def zeros_like(input: Tensor, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def ones_like(input: Tensor, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def randn_like(input: Tensor, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def rand_like(input: Tensor, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def empty_like(input: Tensor, dtype: Any = ..., device: Any = ...) -> Tensor: ...
def full_like(
    input: Tensor, fill_value: float, dtype: Any = ..., device: Any = ...
) -> Tensor: ...
def matmul(input: Tensor, other: Tensor) -> Tensor: ...
def einsum(equation: str, *operands: Tensor) -> Tensor: ...
def relu(input: Tensor) -> Tensor: ...
def sigmoid(input: Tensor) -> Tensor: ...
def tanh(input: Tensor) -> Tensor: ...
def softmax(input: Tensor, dim: int) -> Tensor: ...
def abs(input: Tensor) -> Tensor: ...
def sqrt(input: Tensor) -> Tensor: ...
def exp(input: Tensor) -> Tensor: ...
def log(input: Tensor) -> Tensor: ...
def clamp(input: Tensor, min: float = ..., max: float = ...) -> Tensor: ...
def sum(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def mean(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def max(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def min(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def std(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def var(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def argmax(input: Tensor, dim: int = ..., keepdim: bool = False) -> Tensor: ...
def cat(tensors: list[Tensor] | tuple[Tensor, ...], dim: int = 0) -> Tensor: ...
def stack(tensors: list[Tensor] | tuple[Tensor, ...], dim: int = 0) -> Tensor: ...
def squeeze(input: Tensor, dim: int = ...) -> Tensor: ...
def unsqueeze(input: Tensor, dim: int) -> Tensor: ...
def reshape(input: Tensor, shape: tuple[int, ...]) -> Tensor: ...
def transpose(input: Tensor, dim0: int, dim1: int) -> Tensor: ...
def flatten(input: Tensor, start_dim: int = 0, end_dim: int = -1) -> Tensor: ...
def unbind(input: Tensor, dim: int = 0) -> tuple[Tensor, ...]: ...
