# Copyright (c) Meta Platforms, Inc. and affiliates.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

from typing import TypeVar as _TypeVar

class Dim[T]:
    def __init__(self, value: int) -> None: ...
    def __add__(self, other: Dim) -> Dim: ...
    def __sub__(self, other: Dim) -> Dim: ...
    def __mul__(self, other: Dim) -> Dim: ...
    def __floordiv__(self, other: Dim) -> Dim: ...
    def __mod__(self, other: Dim) -> Dim: ...
    def __int__(self) -> int: ...

def TypeVar(name: str) -> _TypeVar: ...
