# @generated
def greet(name: str) -> str: ...


def add(x: int, y: int) -> int: ...


async def async_fetch(url: str) -> bytes: ...


def with_defaults(x: int, y: int = 0, z: str = "hello") -> None: ...


def complex_defaults(x: int, data: object = ...) -> None: ...


def varargs(*args: int, **kwargs: str) -> None: ...


def pos_only(x: int, y: int, /) -> int: ...


def kw_only(*, key: str, value: int) -> None: ...
